spring.profiles.active=dev

spring.application.name=schoolapp
server.servlet.context-path=/schoolapp

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Το session κλείνει αυτόματα όταν επιστρέφει το service
# αν ήταν true, θα κρατούσε το session ανοιχτό και θα μπορούσε να κάνει lazy loading
# n + 1 queries, OSIV = true
# Best practise είναι false
# JOIN FETCH ή EntityGraph
spring.jpa.open-in-view=false
